import {Quest} from "@/lib/types";

export const questData: Quest[] = [
  {
    id: 'workshop-org',
    title: 'Workshop Organizer',
    description: 'Organize a workshop to share your knowledge with other participants',
    reward: 1,
    type: 'Social',
    difficulty: 'Medium',
  },
  {
    id: 'workshop-participate',
    title: 'Participate in a Workshop',
    description: 'Attend and actively participate in a workshop',
    reward: 1,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'competition-3-days',
    title: 'Competition All 3 Days',
    description: 'Join the competition and participate on all 3 days',
    reward: 1,
    type: 'Challenge',
    difficulty: 'Hard',
  },
  {
    id: 'win-1st-3rd',
    title: 'Win 1st to 3rd Place',
    description: 'Place 1st, 2nd, or 3rd in the competition',
    reward: 1,
    type: 'Challenge',
    difficulty: 'Hard',
  },
  {
    id: 'voted-project-win',
    title: 'Win Voted Project',
    description: 'Win the participant-voted project award',
    reward: 1,
    type: 'Challenge',
    difficulty: 'Medium',
  },
  {
    id: 'best-vibes',
    title: 'Best Vibes',
    description: 'Be voted as having the best vibes at the event',
    reward: 1,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'kahoot',
    title: 'Kahoot!',
    description: 'Participate in the Kahoot! game',
    reward: 1,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'gartic-phone',
    title: 'Gartic Phone',
    description: 'Participate in the Gartic Phone game',
    reward: 1,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'create-calc-app',
    title: 'Create a Calculator App',
    description: 'Create a functional calculator app during the event',
    reward: 1,
    type: 'Challenge',
    difficulty: 'Medium',
  },
  {
    id: 'public-execution',
    title: 'Public Execution',
    description: 'Perform a task or challenge in front of an audience',
    reward: 1,
    type: 'Challenge',
    difficulty: 'Hard',
  },
  {
    id: 'wikispeedia-winner',
    title: 'Wikispeedia Champion',
    description: 'Be the first to win a round of Wikispeedia',
    reward: 1,
    type: 'Social',
    difficulty: 'Easy',
  },
];