import {Quest} from "@/lib/types";

export const questData: Quest[] = [
  {
    id: 'workshop-org',
    title: 'Workshop Organizer',
    description: 'Organize a workshop to share your knowledge with other participants',
    reward: 40,
    type: 'Social',
    difficulty: 'Medium',
  },
  {
    id: 'workshop-participate',
    title: 'Participate in a Workshop',
    description: 'Attend and actively participate in a workshop',
    reward: 5,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'competition-3-days',
    title: 'Competition All 3 Days',
    description: 'Join the competition and participate on all 3 days',
    reward: 10,
    type: 'Challenge',
    difficulty: 'Hard',
  },
  {
    id: 'win-1st',
    title: 'Win 1st',
    description: 'Place 1st in the competition (Points will be split between winners)',
    reward: 120,
    type: 'Challenge',
    difficulty: 'Hard',
  },
    {
    id: 'win-2nd',
    title: 'Win 2nd',
    description: 'Place 2nd in the competition (Points will be split between winners)',
    reward: 90,
    type: 'Challenge',
    difficulty: 'Hard',
  },
    {
    id: 'win-3rd',
    title: 'Win 3rd',
    description: 'Place 3rd in the competition (Points will be split between winners)',
    reward: 60,
    type: 'Challenge',
    difficulty: 'Hard',
  },
  {
    id: 'voted-project-win',
    title: 'Win Voted Project',
    description: 'Win the participant-voted project award',
    reward: 30,
    type: 'Challenge',
    difficulty: 'Medium',
  },
  {
    id: 'best-vibes',
    title: 'Best Vibes',
    description: 'Be voted as having the best vibes at the event',
    reward: 5,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'blooket',
    title: 'Blooket!',
    description: 'Win in the Blooket game!',
    reward: 10,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'gartic-phone',
    title: 'Gartic Phone',
    description: 'Participate in the Gartic Phone game',
    reward: 5,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'create-calc-app',
    title: 'Create a Calculator App',
    description: 'Create a functional calculator app during the event',
    reward: 10,
    type: 'Challenge',
    difficulty: 'Medium',
  },
  {
    id: 'wikispeedia-winner',
    title: 'Wikispeedia Champion',
    description: 'Be the first to win a round of Wikispeedia',
    reward: 10,
    type: 'Social',
    difficulty: 'Easy',
  },
  {
    id: 'public-execution',
    title: 'Public Execution',
    description: 'Yep, you heard that right ;) (feat. layal)',
    reward: 0,
    type: 'Challenge',
    difficulty: 'Hard',
  },
];