import {StoreItemType} from "@/lib/types";

export const storeItems: StoreItemType[] = [
  {
    id: 'checkpoint-hoodie',
    name: 'Checkpoint Hoodie',
    description: 'Premium quality hoodie with embroidered Checkpoint logo. Perfect for coding sessions.',
    img: 'https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 5,
    startingBid: 500,
    category: 'Merch',
    rarity: 'Rare',
  },
  {
    id: 'wireless-earbuds',
    name: 'Code Beat Wireless Earbuds',
    description: 'High-quality wireless earbuds for your coding soundtrack. Noise-cancelling technology included.',
    img: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 8,
    startingBid: 300,
    category: 'Tech',
    rarity: 'Common',
  },
  {
    id: 'mechanical-keyboard',
    name: 'Hacker\'s Delight Keyboard',
    description: 'RGB mechanical keyboard with custom Checkpoint keycaps. Tactile switches for optimal typing.',
    img: 'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 3,
    startingBid: 800,
    category: 'Tech',
    rarity: 'Epic',
  },
  {
    id: 'limited-tshirt',
    name: 'Limited Edition Hackathon Tee',
    description: 'Exclusive t-shirt commemorating this year\'s hackathon. Only available to participants.',
    img: 'https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 12,
    startingBid: 200,
    category: 'Merch',
    rarity: 'Common',
  },
  {
    id: 'gaming-mouse',
    name: 'Precision Gaming Mouse',
    description: 'High-DPI gaming mouse with programmable buttons. Perfect for design work and gaming.',
    img: 'https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 6,
    startingBid: 400,
    category: 'Tech',
    rarity: 'Rare',
  },
  {
    id: 'mentor-session',
    name: '1-on-1 Industry Mentor Session',
    description: 'Private mentoring session with a senior developer from top tech companies. Career guidance included.',
    img: 'https://images.pexels.com/photos/3184291/pexels-photo-3184291.jpeg?auto=compress&cs=tinysrgb&w=400',
    stock: 2,
    startingBid: 1000,
    category: 'Experience',
    rarity: 'Legendary',
  },
];