import {StoreItemType} from "@/lib/types";

export const storeItems: StoreItemType[] = [
    {
        id: 'gambling',
        name: '50 checkpoints - Social Experiment',
        description: 'Auction for 50 checkpoints, with a twist.. the second highest bidder will still pay half of the bid price..',
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXQCHVOYummIswMByVkLOwVzPDIFpcH84_XA&s',
        stock: 1,
        startingBid: 1,
        category: 'Experience',
        rarity: 'Legendary',
    },
    {
        id: 'dino',
        name: 'TRex Lamp',
        description: 'Cool ass TRex lamp.',
        img: 'https://m.media-amazon.com/images/I/719MhxuXSBL._AC_SX679_.jpg',
        stock: 1,
        startingBid: 10,
        category: 'Collectible',
        rarity: 'Common',
    },
    {
        id: 'arduino-sensors-16',
        name: 'Top quality arduino sensors',
        description: '16 powerful arduino sensors in a cool kit.',
        img: 'https://m.media-amazon.com/images/I/713E8ObWJ9L._AC_SL1200_.jpg',
        stock: 1,
        startingBid: 40,
        category: 'Tech',
        rarity: 'Rare',
    },
    {
        id: 'arduino-sensors-235',
        name: 'Arduino Bundle Kit',
        description: 'Gigantic kit of items like resistors etc with 235 separate items',
        img: 'https://m.media-amazon.com/images/I/716K4aanQaL._AC_SL1018_.jpg',
        stock: 1,
        startingBid: 50,
        category: 'Tech',
        rarity: 'Epic',
    },
    {
        id: 'solder',
        name: 'Soldering kit',
        description: 'Full soldering kit with everything you need to start.',
        img: 'https://m.media-amazon.com/images/I/71FhJwxdx1S._AC_SX569_.jpg',
        stock: 2,
        startingBid: 40,
        category: 'Tech',
        rarity: 'Rare',
    },
    {
        id: 'cute-dino',
        name: 'Dino lamp',
        description: 'Lamp shaped as a dino',
        img: 'https://m.media-amazon.com/images/I/41aDuGHXTOL._AC_SX569_.jpg',
        stock: 1,
        startingBid: 20,
        category: 'Collectible',
        rarity: 'Legendary',
    },
    {
        id: 'keyboard',
        name: 'Gaming Keyboard',
        description: 'Cool rgb black wired gaming keyboard.',
        img: 'https://m.media-amazon.com/images/I/71auXf8QKgL._AC_SX450_.jpg',
        stock: 3,
        startingBid: 25,
        category: 'Merch',
        rarity: 'Rare',
    }, {
        id: 'mouse',
        name: 'Gaming Mouse',
        description: 'Cool rgb black wired gaming mouse.',
        img: 'https://m.media-amazon.com/images/I/71auXf8QKgL._AC_SX450_.jpg',
        stock: 3,
        startingBid: 15,
        category: 'Merch',
        rarity: 'Rare',
    },
];